import formSchema from "@/schema/form";
import { z } from "zod";

export type Person = z.infer<typeof formSchema>;

export const people: Person[] = [
  {
    name: "Isaac Kwabena",
    dob: "1985-04-15",
    gender: "Male",
    cell: "Faith",
    residentialAddress: "GA-183-456",
    mobile: "0591234567",
    maritalStatus: "Married",
    spouseName: "Grace Kwabena",
    numberOfChildren: "3",
    numberOfOtherHouseholdMembers: "1",
    occupation: "Engineer",
    contactPerson: "Kofi Mensah",
    Remarks: "Faithful member",
    ghanaCardID: "GHA-123456789-1",
    picture: "https://example.com/photo1.jpg",
  },
  {
    name: "Adwoa Agyeman",
    dob: "1990-08-21",
    gender: "Female",
    cell: "Joy",
    residentialAddress: "GA-183-456",
    mobile: "0509876543",
    maritalStatus: "Single",
    spouseName: "",
    numberOfChildren: "0",
    numberOfOtherHouseholdMembers: "2",
    occupation: "Teacher",
    contactPerson: "Ama Agyeman",
    Remarks: "Active in church",
    ghanaCardID: "GHA-987654321-1",
    picture: "https://example.com/photo2.jpg",
  },
  {
    name: "Kwame Opoku",
    dob: "1979-11-02",
    gender: "Male",
    cell: "Peace",
    residentialAddress: "GA-183-456",
    mobile: "0231122334",
    maritalStatus: "Married",
    spouseName: "Abena Opoku",
    numberOfChildren: "4",
    numberOfOtherHouseholdMembers: "2",
    occupation: "Farmer",
    contactPerson: "Yaw Mensah",
    Remarks: "Quiet but regular",
    ghanaCardID: "GHA-223344556-1",
    picture: "https://example.com/photo3.jpg",
  },
  {
    name: "Abena Mensah",
    dob: "1988-05-17",
    gender: "Female",
    cell: "Love",
    residentialAddress: "GA-183-456",
    mobile: "0245566778",
    maritalStatus: "Married",
    spouseName: "Kofi Mensah",
    numberOfChildren: "2",
    numberOfOtherHouseholdMembers: "3",
    occupation: "Trader",
    contactPerson: "Ama Opoku",
    Remarks: "Very dedicated",
    ghanaCardID: "GHA-445566778-1",
    picture: "https://example.com/photo4.jpg",
  },
  {
    name: "Yaw Asante",
    dob: "1995-12-12",
    gender: "Male",
    cell: "Grace",
    residentialAddress: "GA-183-456",
    mobile: "0593344556",
    maritalStatus: "Single",
    spouseName: "",
    numberOfChildren: "0",
    numberOfOtherHouseholdMembers: "1",
    occupation: "Student",
    contactPerson: "Akosua Asante",
    Remarks: "Active youth member",
    ghanaCardID: "GHA-667788990-1",
    picture: "https://example.com/photo5.jpg",
  },
  {
    name: "Akosua Osei",
    dob: "1982-02-14",
    gender: "Female",
    cell: "Hope",
    residentialAddress: "GA-183-456",
    mobile: "0236677889",
    maritalStatus: "Married",
    spouseName: "Yaw Osei",
    numberOfChildren: "3",
    numberOfOtherHouseholdMembers: "4",
    occupation: "Nurse",
    contactPerson: "Ama Osei",
    Remarks: "Very supportive",
    ghanaCardID: "GHA-889900112-1",
    picture: "https://example.com/photo6.jpg",
  },
  {
    name: "Kofi Amankwah",
    dob: "1987-03-23",
    gender: "Male",
    cell: "Faith",
    residentialAddress: "GA-183-456",
    mobile: "0501234567",
    maritalStatus: "Single",
    spouseName: "",
    numberOfChildren: "0",
    numberOfOtherHouseholdMembers: "0",
    occupation: "Driver",
    contactPerson: "Yaw Amankwah",
    Remarks: "New member",
    ghanaCardID: "GHA-001122334-1",
    picture: "https://example.com/photo7.jpg",
  },
  {
    name: "Ama Kwarteng",
    dob: "1992-06-09",
    gender: "Female",
    cell: "Hope",
    residentialAddress: "GA-183-456",
    mobile: "0599876543",
    maritalStatus: "Single",
    spouseName: "",
    numberOfChildren: "0",
    numberOfOtherHouseholdMembers: "2",
    occupation: "Banker",
    contactPerson: "Kofi Kwarteng",
    Remarks: "Always helping others",
    ghanaCardID: "GHA-223344445-1",
    picture: "https://example.com/photo8.jpg",
  },
  {
    name: "Kwabena Nkrumah",
    dob: "1984-11-30",
    gender: "Male",
    cell: "Peace",
    residentialAddress: "GA-183-456",
    mobile: "0249876543",
    maritalStatus: "Married",
    spouseName: "Efua Nkrumah",
    numberOfChildren: "1",
    numberOfOtherHouseholdMembers: "1",
    occupation: "Teacher",
    contactPerson: "Yaw Nkrumah",
    Remarks: "Strong in faith",
    ghanaCardID: "GHA-556677788-1",
    picture: "https://example.com/photo9.jpg",
  },
  {
    name: "Efua Addo",
    dob: "1975-09-14",
    gender: "Female",
    cell: "Joy",
    residentialAddress: "GA-183-456",
    mobile: "0234455667",
    maritalStatus: "Married",
    spouseName: "Kwame Addo",
    numberOfChildren: "5",
    numberOfOtherHouseholdMembers: "2",
    occupation: "Chef",
    contactPerson: "Ama Addo",
    Remarks: "Cooks for the church",
    ghanaCardID: "GHA-778899001-1",
    picture: "https://example.com/photo10.jpg",
  },
];
